[workspace]
channels = ["conda-forge"]
name = "EnerGNN"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[system-requirements]
cuda = "13"

[dependencies]
python = "3.12.*"
wandb = ">=0.23.1,<0.24"
numpy = ">=2.4.1,<3"
tqdm = ">=4.67.1,<5"
ase = ">=3.27.0,<4"
pytorch = ">=2.9.1,<3"
pymatgen = ">=2025.10.7,<2026"
pymatviz = ">=0.17.4,<0.18"
pip = ">=26.0.1,<27"
pysnooper = ">=1.2.1,<2"
pixi-pycharm = ">=0.0.10,<0.0.11"
ipykernel = ">=7.2.0,<8"
optimade = ">=1.4.1,<2"

[pypi-dependencies]
ultraimport = ">=0.1.0, <0.2"
torch-geometric = ">=2.7.0, <3"
# matbench-discovery = ">=1.3.1"   # Please install this from github.
